[workspace]
resolver = "2"
members = [
    "crates/bible-app",
    "crates/bible-app-db",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[workspace.dependencies]
rusqlite = { version = "0.32", features = ["bundled"] }
thiserror = "2"
relm4 = { version = "0.11", features = ["libadwaita", "gnome_47"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "6"
flate2 = "1"
