[package]
name = "bible-app-import"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "bible-app-import"
path = "src/main.rs"

[dependencies]
bible-app-db = { path = "../bible-app-db" }
clap.workspace = true
encoding_rs.workspace = true
memmap2.workspace = true
rusqlite.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
